# Generated by Django 4.2.24 on 2025-09-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_auto_20190407_1414'),
        ('donors', '0002_initial'),
    ]

    operations = [
    ]
